name: Ejecutar script cada noche

on:
  schedule:
    - cron: '0 2 * * *'  # Esto ejecutará a las 2:00 AM UTC
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Usa la versión que necesites

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar main.py
        run: python CSIC_Internship/main.py  # Ruta correcta al script
